#pragma once
#include <Arduino.h>
#include "epd_driver.h"

// Font declarations — generated by fontconvert.py (see fonts/ directory)
extern const GFXfont NotoSansKR_8;
extern const GFXfont NotoSansKR_12;
extern const GFXfont NotoSansKR_16;
extern const GFXfont NotoSansKR_24;
extern const GFXfont NotoSansKR_36;

// ── Drawing helpers ───────────────────────────────────────────────────────────

// Draw text at (x, y) where y is the baseline. Returns the new cursor_x.
int32_t rutil_text(const GFXfont *font, const char *str,
                   int32_t x, int32_t y, uint8_t *fb);

// Draw text centered horizontally within [x, x+w].
void rutil_textCentered(const GFXfont *font, const char *str,
                        int32_t x, int32_t w, int32_t baseline, uint8_t *fb);

// Draw text right-aligned ending at x_right.
void rutil_textRight(const GFXfont *font, const char *str,
                     int32_t x_right, int32_t baseline, uint8_t *fb);

// Draw a filled rectangle in the framebuffer.
void rutil_fillRect(int32_t x, int32_t y, int32_t w, int32_t h,
                    uint8_t color, uint8_t *fb);

// Draw a horizontal rule.
void rutil_hline(int32_t x, int32_t y, int32_t len, uint8_t color, uint8_t *fb);

// Draw a vertical rule.
void rutil_vline(int32_t x, int32_t y, int32_t len, uint8_t color, uint8_t *fb);

// Get text pixel width without drawing.
int32_t rutil_textWidth(const GFXfont *font, const char *str);

// Format time_t to "HH:MM" in local time.
void rutil_fmtTime(time_t t, char *buf, size_t len);

// Format time_t to "HH:MM - HH:MM".
void rutil_fmtTimeRange(time_t start, time_t end, char *buf, size_t len);

// Format time_t to "M월 D일 (요일)" e.g. "4월 22일 (수)".
void rutil_fmtDateKo(time_t t, char *buf, size_t len);

// Format time_t to full date+weekday header e.g. "2026년 4월 22일 수요일".
void rutil_fmtDateHeaderKo(time_t t, char *buf, size_t len);

// Ellipsize str to fit within max_px pixels using font, writing into out.
void rutil_ellipsize(const GFXfont *font, const char *str,
                     int32_t max_px, char *out, size_t outLen);

// Draw UTF-8 text wrapping at character boundaries within maxW pixels.
// baseY: baseline of the first line. lineH: pixels between baselines.
// Stops before drawing a line whose baseline > stopY.
// Returns the Y position of the next line after the last drawn line.
// Pass fb=nullptr to measure only (no drawing).
int32_t rutil_textWrap(const GFXfont *font, const char *str,
                       int32_t x, int32_t maxW, int32_t baseY,
                       int32_t lineH, int32_t stopY, uint8_t *fb);
